version: "3.9"
services: 
  mongo:
    image: "mongo"
    restart: "always"
    environment: 
      MONGO_INITDB_DATABASE: "root_db"
    volumes: 
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
  app:
    image: "vueexpresstodos:latest"
    restart: "always"
    ports: 
      - 4001:4001
    environment: 
      PORT: "4001"
    